FREE = 0
NOBODY = 0
PLAYER_1 = 1
PLAYER_2 = 2
PLAYER_1_WINS = 1
PLAYER_2_WINS = 2
DRAW = 3
NOT_TERMINATED = 0
PLAYER_1_COLOR = 'red'
PLAYER_2_COLOR = 'green'
PLAYER_1_SYMB = 'O'
PLAYER_2_SYMB = 'X'
    
GAME_ROWS = 6
GAME_COLS = 7
